import type {TransactionContext} from "@/lib/infrastructure/transaction";import type {BookingTransactionRepository,CommercialAllocation} from "./repository";
export class PostgresBookingRepository implements BookingTransactionRepository{
 async claimIdempotency(tx:TransactionContext,userId:string,key:string,requestHash:string){const rows=await tx.query<{request_hash:string;status:string}>("SELECT request_hash,status FROM booking_idempotency WHERE user_id=$1 AND idempotency_key=$2 FOR UPDATE",[userId,key]);if(rows[0]){if(rows[0].request_hash!==requestHash)return "CONFLICT" as const;return rows[0].status==="COMPLETED"?"REPLAY" as const:"IN_PROGRESS" as const}const r=await tx.execute("INSERT INTO booking_idempotency(id,user_id,idempotency_key,request_hash,status,expires_at) VALUES(gen_random_uuid(),$1,$2,$3,'PROCESSING',now()+interval '24 hours') ON CONFLICT(user_id,idempotency_key) DO NOTHING",[userId,key,requestHash]);return r.rowCount===1?"CLAIMED" as const:"IN_PROGRESS" as const}
 async getCompletedIdempotentBooking(tx:TransactionContext,userId:string,key:string){const r=await tx.query<{booking_id:string;booking_ref:string}>("SELECT b.id booking_id,b.booking_ref FROM booking_idempotency i JOIN bookings b ON b.id=i.booking_id WHERE i.user_id=$1 AND i.idempotency_key=$2 AND i.status='COMPLETED'",[userId,key]);return r[0]?{bookingId:r[0].booking_id,bookingRef:r[0].booking_ref}:null}
 async lockAvailability(tx:TransactionContext,id:string){const r=await tx.query<{remaining:number|null}>("SELECT remaining FROM availability WHERE id=$1 FOR UPDATE",[id]);if(!r[0])throw new Error("AVAILABILITY_NOT_FOUND");return r[0]}
 async reserveInventory(tx:TransactionContext,id:string,quantity:number){const current=await tx.query<{remaining:number|null;version:number}>("SELECT remaining,version FROM availability WHERE id=$1",[id]);if(!current[0])return null as never;if(current[0].remaining===null)return {remaining:null,version:current[0].version};const r=await tx.query<{remaining:number;version:number}>("UPDATE availability SET remaining=remaining-$2,version=version+1 WHERE id=$1 AND remaining >= $2 RETURNING remaining,version",[id,quantity]);return r[0]??null as never}
 async lockPartnerTrial(tx:TransactionContext,partnerId:string){await tx.query("SELECT id FROM partners WHERE id=$1 FOR UPDATE",[partnerId])}
 async allocateCommercialPath(tx:TransactionContext,input:{partnerId:string}):Promise<CommercialAllocation>{
  // Partner row is already locked by the orchestrator, serializing trial allocation per Partner.
  const occupied=await tx.query<{trial_ordinal:number}>("SELECT trial_ordinal FROM partner_trial_ledger WHERE partner_id=$1 AND status IN ('RESERVED','CONSUMED') AND trial_ordinal IS NOT NULL ORDER BY trial_ordinal",[input.partnerId]);
  const used=new Set(occupied.map(x=>x.trial_ordinal));let ordinal:number|undefined;for(let i=1;i<=5;i++){if(!used.has(i)){ordinal=i;break}}
  if(ordinal!==undefined)return {path:"TRIAL_FREE",ordinal};
  // Exact commission rate is intentionally not selected here; persistence requires an approved versioned rule.
  return {path:"COMMISSIONABLE",ruleVersion:"UNRESOLVED"};
 }
 async createBooking(tx:TransactionContext,input:Parameters<BookingTransactionRepository["createBooking"]>[1]){
  if(input.commercial.path==="COMMISSIONABLE"&&input.commercial.ruleVersion==="UNRESOLVED")throw new Error("COMMISSION_RULE_NOT_CONFIGURED");
  const ids=await tx.query<{id:string}>("SELECT gen_random_uuid() id");const bookingId=ids[0].id;const bookingRef="LT-"+bookingId.replace(/-/g,"").slice(0,12).toUpperCase();
  await tx.execute("INSERT INTO bookings(id,booking_ref,user_id,status,payment_status) VALUES($1,$2,$3,'PENDING','PENDING')",[bookingId,bookingRef,input.userId]);
  await tx.execute("INSERT INTO booking_items(id,booking_id,service_id,availability_id,quantity) VALUES(gen_random_uuid(),$1,$2,$3,$4)",[bookingId,input.serviceId,input.availabilityId,input.quantity]);
  await tx.execute("INSERT INTO price_snapshots(booking_id,price_quote_id,currency,base_amount,fees_amount,coupon_amount,points_benefit_amount,customer_total,commission_rule_version) VALUES($1,$9::uuid,$2,$3::bigint,$4::bigint,$5::bigint,$6::bigint,$7::bigint,$8)",[bookingId,input.price.currency,input.price.baseAmount,input.price.feesAmount,input.price.couponAmount,input.price.pointsBenefitAmount,input.price.customerTotal,input.commercial.path==="COMMISSIONABLE"?input.commercial.ruleVersion:null,input.price.priceQuoteId]);
  return {bookingId,bookingRef};
 }
 async persistCommercialPath(tx:TransactionContext,input:{bookingId:string;partnerId:string;commercial:CommercialAllocation}){if(input.commercial.path==="COMMISSIONABLE"){if(!input.commercial.ruleVersion||input.commercial.ruleVersion==="UNRESOLVED")throw new Error("COMMISSION_RULE_NOT_CONFIGURED");throw new Error("COMMISSION_AMOUNT_PERSISTENCE_NOT_WIRED")}await tx.execute("INSERT INTO partner_booking_commercial_paths(booking_id,partner_id,path) VALUES($1,$2,'TRIAL_FREE')",[input.bookingId,input.partnerId]);await tx.execute("INSERT INTO partner_trial_ledger(id,partner_id,booking_id,commercial_path,trial_ordinal,status) VALUES(gen_random_uuid(),$1,$2,'TRIAL_FREE',$3,'RESERVED')",[input.partnerId,input.bookingId,input.commercial.ordinal])}
 async attachInventoryToBooking(tx:TransactionContext,input:Parameters<BookingTransactionRepository["attachInventoryToBooking"]>[1]){await tx.execute("INSERT INTO inventory_holds(id,service_id,availability_id,booking_id,quantity,status,expires_at) SELECT gen_random_uuid(),service_id,$2,$1,$3,'ACTIVE',now()+($4::text || ' minutes')::interval FROM availability WHERE id=$2",[input.bookingId,input.availabilityId,input.quantity,input.holdMinutes])}
 async completeIdempotency(tx:TransactionContext,input:{userId:string;key:string;bookingId:string}){await tx.execute("UPDATE booking_idempotency SET booking_id=$3,status='COMPLETED' WHERE user_id=$1 AND idempotency_key=$2 AND status='PROCESSING'",[input.userId,input.key,input.bookingId])}
 async writeAudit(tx:TransactionContext,input:{actorUserId:string;action:string;targetType:string;targetId:string}){await tx.execute("INSERT INTO audit_logs(id,actor_user_id,action,target_type,target_id) VALUES(gen_random_uuid(),$1,$2,$3,$4)",[input.actorUserId,input.action,input.targetType,input.targetId])}
}
