import type {TransactionContext} from "@/lib/infrastructure/transaction";import type {BookingTransactionRepository,CommercialAllocation} from "./repository";
export class PostgresBookingRepository implements BookingTransactionRepository{
 async claimIdempotency(tx:TransactionContext,userId:string,key:string,requestHash:string){const rows=await tx.query<{request_hash:string;status:string}>("SELECT request_hash,status FROM booking_idempotency WHERE user_id=$1 AND idempotency_key=$2 FOR UPDATE",[userId,key]);if(rows[0]){if(rows[0].request_hash!==requestHash)return "CONFLICT" as const;return rows[0].status==="COMPLETED"?"REPLAY" as const:"IN_PROGRESS" as const}const r=await tx.execute("INSERT INTO booking_idempotency(id,user_id,idempotency_key,request_hash,status,expires_at) VALUES(gen_random_uuid(),$1,$2,$3,'PROCESSING',now()+interval '24 hours') ON CONFLICT(user_id,idempotency_key) DO NOTHING",[userId,key,requestHash]);return r.rowCount===1?"CLAIMED" as const:"IN_PROGRESS" as const}
 async getCompletedIdempotentBooking(tx:TransactionContext,userId:string,key:string){const r=await tx.query<{booking_id:string;booking_ref:string}>("SELECT b.id booking_id,b.booking_ref FROM booking_idempotency i JOIN bookings b ON b.id=i.booking_id WHERE i.user_id=$1 AND i.idempotency_key=$2 AND i.status='COMPLETED'",[userId,key]);return r[0]?{bookingId:r[0].booking_id,bookingRef:r[0].booking_ref}:null}
 async lockAvailability(tx:TransactionContext,id:string){const r=await tx.query<{remaining:number|null}>("SELECT remaining FROM availability WHERE id=$1 FOR UPDATE",[id]);if(!r[0])throw new Error("AVAILABILITY_NOT_FOUND");return r[0]}
 async reserveInventory(tx:TransactionContext,id:string,quantity:number){const current=await tx.query<{remaining:number|null;version:number}>("SELECT remaining,version FROM availability WHERE id=$1",[id]);if(!current[0])return null as never;if(current[0].remaining===null)return {remaining:null,version:current[0].version};const r=await tx.query<{remaining:number;version:number}>("UPDATE availability SET remaining=remaining-$2,version=version+1 WHERE id=$1 AND remaining >= $2 RETURNING remaining,version",[id,quantity]);return r[0]??null as never}
 async lockPartnerTrial(tx:TransactionContext,partnerId:string){await tx.query("SELECT id FROM partners WHERE id=$1 FOR UPDATE",[partnerId])}
 async allocateCommercialPath(tx:TransactionContext,input:{partnerId:string}):Promise<CommercialAllocation>{
  // Partner row is already locked by the orchestrator, serializing trial allocation per Partner.
  const occupied=await tx.query<{trial_ordinal:number}>("SELECT trial_ordinal FROM partner_trial_ledger WHERE partner_id=$1 AND status IN ('RESERVED','CONSUMED') AND trial_ordinal IS NOT NULL ORDER BY trial_ordinal",[input.partnerId]);
  const used=new Set(occupied.map(x=>x.trial_ordinal));let ordinal:number|undefined;for(let i=1;i<=5;i++){if(!used.has(i)){ordinal=i;break}}
  if(ordinal!==undefined)return {path:"TRIAL_FREE",ordinal};
  // Exact commission rate is intentionally not selected here; persistence requires an approved versioned rule.
  return {path:"COMMISSIONABLE",ruleVersion:"UNRESOLVED"};
 }
 async createBooking(_tx:TransactionContext,_input:Parameters<BookingTransactionRepository["createBooking"]>[1]){throw new Error("BOOKING_PERSISTENCE_NOT_WIRED")}
 async attachInventoryToBooking(_tx:TransactionContext,_input:Parameters<BookingTransactionRepository["attachInventoryToBooking"]>[1]){throw new Error("INVENTORY_HOLD_PERSISTENCE_NOT_WIRED")}
 async completeIdempotency(tx:TransactionContext,input:{userId:string;key:string;bookingId:string}){await tx.execute("UPDATE booking_idempotency SET booking_id=$3,status='COMPLETED' WHERE user_id=$1 AND idempotency_key=$2 AND status='PROCESSING'",[input.userId,input.key,input.bookingId])}
 async writeAudit(tx:TransactionContext,input:{actorUserId:string;action:string;targetType:string;targetId:string}){await tx.execute("INSERT INTO audit_logs(id,actor_user_id,action,target_type,target_id) VALUES(gen_random_uuid(),$1,$2,$3,$4)",[input.actorUserId,input.action,input.targetType,input.targetId])}
}
