-- LaosTravel desired-state schema notice
--
-- This file previously duplicated an early schema snapshot and became stale
-- (legacy PENDING payment status, five-booking trial and pre-discount pricing).
-- It is intentionally no longer a second executable source of truth.
--
-- AUTHORITATIVE DATABASE DEFINITION:
--   Apply db/migrations in numeric order through the latest migration.
--   CI executes scripts/run-db-bootstrap.mjs to prove a clean database can be
--   constructed from that migration chain.
--
-- Current cross-client business vocabulary and authority boundaries:
--   docs/backend/canonical-cross-platform-contract-v1.md
--
-- Historical tables/columns retained by migrations may exist for audit and
-- backward compatibility. Their presence does not reactivate superseded
-- commercial policy.
