import type { Locale } from "./locales";
export type Messages={nav:{explore:string;stays:string;activities:string;transport:string;map:string;signIn:string};hero:{eyebrow:string;title:string;subtitle:string;destination:string;dates:string;guests:string;search:string};home:{plan:string;journey:string;emergency:string;emergencyHint:string;viewContacts:string;popular:string;seeAll:string;localGuide:string;exploreVangVieng:string;exploreText:string;startExploring:string;getAround:string;findTransport:string;transportText:string;from:string;to:string;date:string;find:string;partner:string;grow:string;partnerText:string;becomePartner:string};services:string[]};
const en:Messages={nav:{explore:"Explore",stays:"Stays",activities:"Activities",transport:"Transport",map:"Map",signIn:"Sign in"},hero:{eyebrow:"DISCOVER LAOS",title:"Explore Laos",subtitle:"Stunning nature. Rich culture. Unforgettable journeys.",destination:"Where do you want to go?",dates:"Dates",guests:"Guests",search:"Search"},home:{plan:"PLAN YOUR TRIP",journey:"Everything for your journey",emergency:"Emergency Assistance",emergencyHint:"Verified Vang Vieng contact numbers",viewContacts:"View contacts",popular:"Popular right now",seeAll:"See all",localGuide:"LOCAL GUIDE",exploreVangVieng:"Explore Vang Vieng",exploreText:"Nature, adventure, food, culture and relaxing experiences — all in one place.",startExploring:"Start exploring",getAround:"GET AROUND",findTransport:"Find your transport",transportText:"Plan local transfers and intercity journeys from one trusted platform.",from:"From",to:"To",date:"Date",find:"Find transport",partner:"LAOSTRAVEL PARTNER",grow:"Grow with LaosTravel",partnerText:"Manage your services, availability and bookings through one platform.",becomePartner:"Become a Partner"},services:["Hotels","Restaurants","Attractions","Tours & Activities","Transport","Map","Car Rental","Guides"]};
export const messages:Record<Locale,Messages>={
en,
lo:{...en,nav:{explore:"ສຳຫຼວດ",stays:"ທີ່ພັກ",activities:"ກິດຈະກຳ",transport:"ການເດີນທາງ",map:"ແຜນທີ່",signIn:"ເຂົ້າລະບົບ"},hero:{eyebrow:"ຄົ້ນພົບລາວ",title:"ທ່ຽວລາວ",subtitle:"ທຳມະຊາດງົດງາມ ວັດທະນະທຳອຸດົມສົມບູນ ການເດີນທາງທີ່ໜ້າຈົດຈຳ",destination:"ທ່ານຢາກໄປໃສ?",dates:"ວັນທີ",guests:"ຜູ້ເດີນທາງ",search:"ຄົ້ນຫາ"},services:["ໂຮງແຮມ","ຮ້ານອາຫານ","ສະຖານທີ່ທ່ຽວ","ທົວ & ກິດຈະກຳ","ລົດຮັບສົ່ງ","ແຜນທີ່","ລົດເຊົ່າ","ໄກດ໌"]},
th:{...en,nav:{explore:"สำรวจ",stays:"ที่พัก",activities:"กิจกรรม",transport:"การเดินทาง",map:"แผนที่",signIn:"เข้าสู่ระบบ"},hero:{eyebrow:"ค้นพบลาว",title:"เที่ยวลาว",subtitle:"ธรรมชาติสวยงาม วัฒนธรรมหลากหลาย การเดินทางที่น่าจดจำ",destination:"คุณอยากไปที่ไหน?",dates:"วันที่",guests:"ผู้เดินทาง",search:"ค้นหา"},services:["โรงแรม","ร้านอาหาร","สถานที่เที่ยว","ทัวร์และกิจกรรม","รถรับส่ง","แผนที่","รถเช่า","ไกด์"]},
vi:{...en,nav:{explore:"Khám phá",stays:"Lưu trú",activities:"Hoạt động",transport:"Di chuyển",map:"Bản đồ",signIn:"Đăng nhập"},hero:{eyebrow:"KHÁM PHÁ LÀO",title:"Khám phá Lào",subtitle:"Thiên nhiên tuyệt đẹp. Văn hóa phong phú. Hành trình khó quên.",destination:"Bạn muốn đi đâu?",dates:"Ngày",guests:"Khách",search:"Tìm kiếm"}},
zh:{...en,nav:{explore:"探索",stays:"住宿",activities:"活动",transport:"交通",map:"地图",signIn:"登录"},hero:{eyebrow:"探索老挝",title:"探索老挝",subtitle:"壮丽自然，丰富文化，难忘旅程。",destination:"您想去哪里？",dates:"日期",guests:"旅客",search:"搜索"}},
fr:{...en,nav:{explore:"Explorer",stays:"Séjours",activities:"Activités",transport:"Transport",map:"Carte",signIn:"Connexion"},hero:{eyebrow:"DÉCOUVRIR LE LAOS",title:"Explorez le Laos",subtitle:"Nature magnifique. Culture riche. Voyages inoubliables.",destination:"Où souhaitez-vous aller ?",dates:"Dates",guests:"Voyageurs",search:"Rechercher"}},
ko:{...en,nav:{explore:"둘러보기",stays:"숙소",activities:"액티비티",transport:"교통",map:"지도",signIn:"로그인"},hero:{eyebrow:"라오스 발견",title:"라오스 여행",subtitle:"아름다운 자연, 풍부한 문화, 잊지 못할 여행.",destination:"어디로 가고 싶으신가요?",dates:"날짜",guests:"인원",search:"검색"}}
};
