import {randomUUID} from "node:crypto";import type {Pool} from "pg";import type {AvailabilityQuote,AvailabilityQuoteRequest} from "@/lib/api/contracts";
export class QuoteUnavailableError extends Error{constructor(public code:string){super(code)}}
export async function createAuthoritativeQuote(pool:Pool,input:AvailabilityQuoteRequest):Promise<AvailabilityQuote>{
 const client=await pool.connect();try{await client.query("BEGIN");
  const av=await client.query<{id:string;remaining:number|null;version:string}>("SELECT id,remaining,version::text FROM availability WHERE service_id=$1 AND starts_at::date=$2::date AND (remaining IS NULL OR remaining>=$3) ORDER BY starts_at NULLS LAST LIMIT 1 FOR SHARE",[input.serviceId,input.date,input.quantity]);if(!av.rows[0])throw new QuoteUnavailableError("AVAILABILITY_NOT_FOUND");
  const offer=await client.query<{unit_amount:string;partner_discount_amount:string}>("SELECT unit_amount::text,partner_discount_amount::text FROM service_price_offers WHERE service_id=$1 AND status='ACTIVE' AND effective_from<=now() AND (effective_until IS NULL OR effective_until>now()) AND (($2::text IS NULL AND option_id IS NULL) OR option_id=$2) ORDER BY effective_from DESC LIMIT 1 FOR SHARE",[input.serviceId,input.optionId??null]);if(!offer.rows[0])throw new QuoteUnavailableError("PRICE_OFFER_NOT_FOUND");
  const unit=BigInt(offer.rows[0].unit_amount),discount=BigInt(offer.rows[0].partner_discount_amount),qty=BigInt(input.quantity);const base=unit*qty,partnerDiscount=discount*qty,total=base-partnerDiscount;
  const id=randomUUID(),token=randomUUID(),expires=new Date(Date.now()+10*60*1000).toISOString();
  await client.query("INSERT INTO price_quotes(id,service_id,availability_id,option_id,service_date,quantity,availability_token,currency,base_amount,fees_amount,partner_discount_amount,coupon_amount,points_benefit_amount,customer_total,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7,'LAK',$8,0,$9,0,0,$10,$11)",[id,input.serviceId,av.rows[0].id,input.optionId??null,input.date,input.quantity,token,base.toString(),partnerDiscount.toString(),total.toString(),expires]);
  await client.query("COMMIT");return {serviceId:input.serviceId,date:input.date,quantity:input.quantity,...(input.optionId?{optionId:input.optionId}:{}),availabilityToken:token,priceQuoteId:id,currency:"LAK",baseAmount:base.toString(),feesAmount:"0",partnerDiscountAmount:partnerDiscount.toString(),couponAmount:"0",pointsBenefitAmount:"0",customerTotal:total.toString(),expiresAt:expires};
 }catch(e){await client.query("ROLLBACK");throw e}finally{client.release()}
}
