const services=[
  ["🏨","Hotels"],["🍽️","Restaurants"],["🏞️","Attractions"],["🧭","Tours & Activities"],
  ["🚐","Transport"],["🗺️","Map"],["🚙","Car Rental"],["🧑‍💼","Guides"]
];
const popular=["Blue Lagoon","Nam Song River","Vang Vieng Mountains"];
export default function Home(){
  return <main>
    <header className="siteHeader"><div className="container headerInner"><a className="brand" href="/" aria-label="LaosTravel home"><span>LA</span><span className="brandFlower">✿</span><span>S</span><b>TRAVEL</b></a><nav className="desktopNav" aria-label="Primary"><a href="#explore">Explore</a><a href="#services">Stays</a><a href="#services">Activities</a><a href="#transport">Transport</a><a href="#explore">Map</a></nav><div className="headerActions"><button className="ghostButton">EN</button><button className="signInButton">Sign in</button></div></div></header>
    <section className="hero"><div className="container heroInner"><div className="heroCopy"><p className="eyebrow">DISCOVER LAOS</p><h1>Explore Laos</h1><p>Stunning nature. Rich culture. Unforgettable journeys.</p></div><div className="searchBar" role="search"><button>Where do you want to go?</button><button>Dates</button><button>Guests</button><button className="searchButton">Search</button></div></div></section>
    <section id="services" className="section container"><div className="sectionHeading"><div><p className="eyebrow">PLAN YOUR TRIP</p><h2>Everything for your journey</h2></div></div><div className="serviceGrid">{services.map(([icon,label])=><a className="serviceCard" href="#" key={label}><span className="serviceIcon" aria-hidden="true">{icon}</span><strong>{label}</strong></a>)}</div><a className="emergencyCard" href="#"><span>＋</span><div><strong>Emergency Assistance</strong><small>Verified Vang Vieng contact numbers</small></div><b>View contacts →</b></a></section>
    <section className="section sectionAlt"><div className="container"><div className="sectionHeading"><div><p className="eyebrow">VANG VIENG</p><h2>Popular right now</h2></div><a className="seeAll" href="#">See all</a></div><div className="popularGrid">{popular.map((name,i)=><article className="placeCard" key={name}><div className={"placeImage placeImage"+(i+1)} aria-label={name}></div><div className="placeBody"><small>Vang Vieng</small><h3>{name}</h3><p>Explore local nature and experiences.</p></div></article>)}</div></div></section>
    <section id="explore" className="section container"><div className="exploreCard"><div><p className="eyebrow">LOCAL GUIDE</p><h2>Explore Vang Vieng</h2><p>Nature, adventure, food, culture and relaxing experiences — all in one place.</p><a className="primaryButton" href="#">Start exploring</a></div></div></section>
    <section id="transport" className="section container"><div className="transportCard"><div><p className="eyebrow">GET AROUND</p><h2>Find your transport</h2><p>Plan local transfers and intercity journeys from one trusted platform.</p></div><div className="transportForm"><button>From</button><button>To</button><button>Date</button><button className="primaryButton">Find transport</button></div></div></section>
    <section className="partnerSection"><div className="container partnerInner"><div><p className="eyebrow light">LAOSTRAVEL PARTNER</p><h2>Grow with LaosTravel</h2><p>Manage your services, availability and bookings through one platform.</p></div><a className="lightButton" href="#">Become a Partner</a></div></section>
    <footer><div className="container footerInner"><div><div className="brand footerBrand"><span>LA</span><span className="brandFlower">✿</span><span>S</span><b>TRAVEL</b></div><p>Explore Laos with confidence.</p></div><div><strong>Explore</strong><a href="#services">Services</a><a href="#explore">Vang Vieng</a><a href="#transport">Transport</a></div><div><strong>Support</strong><a href="#">Emergency</a><a href="#">Help & Support</a><a href="#">Contact</a></div><div><strong>Legal</strong><a href="#">Privacy</a><a href="#">Terms</a></div></div></footer>
  </main>
}
