"use client";
import {FormEvent,useState} from "react";
type Summary={name:string;phone:string;email:string;date:string;guests:string};
export function BookingContactForm(){
 const [summary,setSummary]=useState<Summary|null>(null);const [submissionKey,setSubmissionKey]=useState(()=>crypto.randomUUID());const [status,setStatus]=useState<"idle"|"loading"|"error">("idle");const [error,setError]=useState("");
 async function submit(e:FormEvent<HTMLFormElement>){
  e.preventDefault();setStatus("loading");setError("");const fd=new FormData(e.currentTarget);
  const data={name:String(fd.get("name")||""),phone:String(fd.get("phone")||""),email:String(fd.get("email")||""),date:String(fd.get("date")||""),guests:Number(fd.get("guests")),consent:fd.get("consent")==="on"};
  try{const res=await fetch("/api/v1/tour-leads",{method:"POST",headers:{"content-type":"application/json","idempotency-key":submissionKey},body:JSON.stringify(data)});if(!res.ok){const body=await res.json().catch(()=>null);throw new Error(body?.error?.code||"SUBMISSION_FAILED")}setSummary({...data,guests:String(data.guests)});setSubmissionKey(crypto.randomUUID());setStatus("idle");}
  catch(err){setStatus("error");setError(err instanceof Error&&err.message==="LEAD_STORAGE_NOT_CONFIGURED"?"ระบบรับคำขอจองยังไม่เปิดใช้งาน กรุณาลองใหม่ภายหลัง":"ส่งข้อมูลไม่สำเร็จ กรุณาตรวจสอบข้อมูลและลองใหม่");}
 }
 return <section id="booking-contact" className="tourBookingSection"><div className="container bookingContactGrid"><div><p className="eyebrow">BOOK YOUR VANG VIENG TRIP</p><h2>ส่งข้อมูลเพื่อจองทัวร์</h2><p className="tourLead">กรอกข้อมูลเบื้องต้น ทีมงานจะตรวจสอบบริการและติดต่อกลับเพื่อยืนยันรายละเอียดก่อนการจองจริง</p></div><form className="tourContactForm" onSubmit={submit}><label>ชื่อ<input name="name" required autoComplete="name" maxLength={100}/></label><label>เบอร์โทร<input name="phone" required inputMode="tel" autoComplete="tel" maxLength={24}/></label><label>อีเมล<input name="email" required type="email" autoComplete="email" maxLength={254}/></label><label>วันที่ต้องการเดินทาง<input name="date" required type="date"/></label><label>จำนวนคน<input name="guests" required type="number" min="1" max="100"/></label><label className="consentField"><input name="consent" type="checkbox" required/> <span>ฉันยินยอมให้ LA✿S TRAVEL ใช้ข้อมูลที่กรอกเพื่อติดต่อกลับเกี่ยวกับคำขอนี้</span></label>{status==="error"&&<p className="formError" role="alert">{error}</p>}<button className="primaryButton" type="submit" disabled={status==="loading"}>{status==="loading"?"กำลังส่งข้อมูล…":"ส่งข้อมูลจองทัวร์"}</button><small>การส่งฟอร์มนี้ยังไม่ใช่การยืนยันการจองหรือการชำระเงิน</small></form></div>{summary&&<div className="bookingModalBackdrop" role="presentation" onClick={()=>setSummary(null)}><div className="bookingModal" role="dialog" aria-modal="true" aria-labelledby="booking-success" onClick={e=>e.stopPropagation()}><button className="modalClose" aria-label="ปิด" onClick={()=>setSummary(null)}>×</button><h3 id="booking-success">ได้รับข้อมูลแล้ว</h3><p>เจ้าหน้าที่จะติดต่อกลับโดยเร็วที่สุด</p><dl><dt>ชื่อ</dt><dd>{summary.name}</dd><dt>เบอร์โทร</dt><dd>{summary.phone}</dd><dt>อีเมล</dt><dd>{summary.email}</dd><dt>วันที่เดินทาง</dt><dd>{summary.date}</dd><dt>จำนวนคน</dt><dd>{summary.guests}</dd></dl><button className="primaryButton" onClick={()=>setSummary(null)}>ตกลง</button></div></div>}</section>
}