import Link from "next/link";
import { Brand } from "@/components/Brand";
import { LanguageSwitcher } from "@/components/LanguageSwitcher";
import { messages } from "@/i18n/messages";
import type { Locale } from "@/i18n/locales";
const icons=["🏨","🍽️","🏞️","🧭","🚐","🗺️","🚙","🧑‍💼"];
export function HomePage({locale}:{locale:Locale}){const m=messages[locale];return <main>
<header className="siteHeader"><div className="container headerInner"><Link href={"/"+locale}><Brand/></Link><nav className="desktopNav" aria-label="Primary"><a href="#explore">{m.nav.explore}</a><a href="#services">{m.nav.stays}</a><a href="#services">{m.nav.activities}</a><a href="#transport">{m.nav.transport}</a><a href="#explore">{m.nav.map}</a></nav><div className="headerActions"><LanguageSwitcher locale={locale}/><button className="signInButton">{m.nav.signIn}</button></div></div></header>
<section className="hero"><div className="container heroInner"><div className="heroCopy"><p className="eyebrow">{m.hero.eyebrow}</p><h1>{m.hero.title}</h1><p>{m.hero.subtitle}</p></div><div className="searchBar" role="search"><button>{m.hero.destination}</button><button>{m.hero.dates}</button><button>{m.hero.guests}</button><button className="searchButton">{m.hero.search}</button></div></div></section>
<section id="services" className="section container"><div className="sectionHeading"><div><p className="eyebrow">{m.home.plan}</p><h2>{m.home.journey}</h2></div></div><div className="serviceGrid">{m.services.map((label,i)=><a className="serviceCard" href="#" key={label}><span className="serviceIcon" aria-hidden="true">{icons[i]}</span><strong>{label}</strong></a>)}</div><a className="emergencyCard" href="#"><span>＋</span><div><strong>{m.home.emergency}</strong><small>{m.home.emergencyHint}</small></div><b>{m.home.viewContacts} →</b></a></section>
<section className="section sectionAlt"><div className="container"><div className="sectionHeading"><div><p className="eyebrow">VANG VIENG</p><h2>{m.home.popular}</h2></div><a className="seeAll" href="#">{m.home.seeAll}</a></div><div className="popularGrid">{["Blue Lagoon","Nam Song River","Vang Vieng Mountains"].map((name,i)=><article className="placeCard" key={name}><div className={"placeImage placeImage"+(i+1)}></div><div className="placeBody"><small>Vang Vieng</small><h3>{name}</h3><p>Explore local nature and experiences.</p></div></article>)}</div></div></section>
<section id="explore" className="section container"><div className="exploreCard"><div><p className="eyebrow">{m.home.localGuide}</p><h2>{m.home.exploreVangVieng}</h2><p>{m.home.exploreText}</p><a className="primaryButton" href="#">{m.home.startExploring}</a></div></div></section>
<section id="transport" className="section container"><div className="transportCard"><div><p className="eyebrow">{m.home.getAround}</p><h2>{m.home.findTransport}</h2><p>{m.home.transportText}</p></div><div className="transportForm"><button>{m.home.from}</button><button>{m.home.to}</button><button>{m.home.date}</button><button className="primaryButton">{m.home.find}</button></div></div></section>
<section className="partnerSection"><div className="container partnerInner"><div><p className="eyebrow light">{m.home.partner}</p><h2>{m.home.grow}</h2><p>{m.home.partnerText}</p></div><a className="lightButton" href="#">{m.home.becomePartner}</a></div></section>
<footer><div className="container footerInner"><div><Brand/><p>LaosTravel</p></div><div><strong>{m.nav.explore}</strong><a href="#services">{m.home.journey}</a><a href="#explore">Vang Vieng</a><a href="#transport">{m.nav.transport}</a></div><div><strong>Support</strong><a href="#">{m.home.emergency}</a><a href="#">Help & Support</a><a href="#">Contact</a></div><div><strong>Legal</strong><a href="#">Privacy</a><a href="#">Terms</a></div></div></footer>
</main>}
