import {messages} from "@/i18n/messages";import type {Locale} from "@/i18n/locales";import {BookingContactForm} from "./BookingContactForm";
const icons=["🛏️","🍽️","📍","🧭","🚐","🚙","🗺️","🧑‍💼"];
const places=[{name:"Blue Lagoon",img:"https://unsplash.com/photos/WaLcdddWcyI/download?force=true&w=1000"},{name:"Tham Chang",img:"https://unsplash.com/photos/IIvMEBcxUy8/download?force=true&w=1000"},{name:"Balloon & Kayak",img:"https://unsplash.com/photos/3eBh2jj18gI/download?force=true&w=1000"}];
export function HomePage({locale}:{locale:Locale}){const m=messages[locale];return <main>
<section className="hero vangHero"><div className="container heroInner"><div className="heroCopy"><p className="eyebrow">LA✿S TRAVEL • VANG VIENG</p><h1>{m.home.heroTitle}</h1><p>{m.home.heroSubtitle}</p><a className="primaryButton heroCta" href="#booking-contact">{m.home.heroCta}</a></div></div></section>
<section id="services" className="section container"><div className="sectionHeading"><div><p className="eyebrow">{m.home.plan}</p><h2>{m.home.journey}</h2></div></div><div className="serviceGrid">{m.services.map((label,i)=><a className="serviceCard" href={"/"+locale+"/explore/"+["hotels","restaurants","attractions","activities","transport","car-rental","map","guides"][i]} key={label}><span className="serviceIcon" aria-hidden="true">{icons[i]}</span><strong>{label}</strong></a>)}</div><a className="emergencyCard" href={"/"+locale+"/emergency"}><span>🆘</span><div><strong>{m.home.emergency}</strong><small>{m.home.emergencyHint}</small></div><b>{m.home.viewContacts} →</b></a></section>
<section id="highlights" className="section sectionAlt"><div className="container"><div className="sectionHeading"><div><p className="eyebrow">{m.home.highlightEyebrow}</p><h2>{m.home.highlightTitle}</h2></div></div><div className="popularGrid">{places.map((p,i)=><article className="placeCard" key={p.name}><div className="realPlaceImage" role="img" aria-label={p.name} style={{backgroundImage:`url(${p.img})`}}/><div className="placeBody"><small>Vang Vieng, Laos</small><h3>{p.name}</h3><p>{m.home.placeDescriptions[i]}</p></div></article>)}</div></div></section>
<section id="packages" className="section container"><div className="sectionHeading"><div><p className="eyebrow">{m.home.packageEyebrow}</p><h2>{m.home.packageTitle}</h2></div></div><div className="tourPackageCard"><div><span className="tourBadge">{m.home.packageBadge}</span><h3>{m.home.packageName}</h3><p>{m.home.packageDescription}</p></div><div className="tourPrice"><small>{m.home.startingPrice}</small><strong>{m.home.partnerPrice}</strong><a className="primaryButton" href="#booking-contact">{m.home.inquireBook}</a></div></div></section>
<BookingContactForm/>
</main>}