"use client";import {FormEvent,useRef,useState} from "react";import {ClientError,connectedBackend} from "@/lib/client/connected-backend";import {partnerCategories,type PartnerCategory} from "@/lib/partner/model";
const names:Record<PartnerCategory,string>={hotel:"Hotel",restaurant:"Restaurant",attraction:"Attraction","tour-activity":"Tour / Activity",transport:"Transport","car-rental":"Car Rental",guide:"Guide / Freelancer"};
export function PartnerApplication(){const [notice,setNotice]=useState("");const [busy,setBusy]=useState(false);const pending=useRef<{owner:string;body:Record<string,string>}|null>(null);const lock=useRef(false);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(lock.current)return;lock.current=true;setBusy(true);setNotice("");const form=new FormData(e.currentTarget);
 try{const session=await connectedBackend.session();
  if(!pending.current)pending.current={owner:session.userId,body:Object.fromEntries(["category","businessName","contactName","email","phone","area"].map(k=>[k,String(form.get(k)??"").trim()]).concat([["idempotencyKey",crypto.randomUUID()]]))};
  if(pending.current.owner!==session.userId)throw new Error("ACCOUNT_CHANGED");
  const data=await connectedBackend.apply(pending.current.body);setNotice("Application received for review: "+data.applicationId+". This does not grant selling access.");
 }catch(error){if(error instanceof ClientError&&["PARTNER_APPLICATION_INVALID","VALIDATION_ERROR"].includes(error.code)){pending.current=null;setNotice("Check the application fields before submitting again.")}else setNotice("Application could not be confirmed. Sign in with an active LaosTravel account and retry the same application.")}
 finally{lock.current=false;setBusy(false)}
 }
return <form className="partnerForm" onSubmit={submit}><label>Business category<select disabled={busy||pending.current!==null} name="category" required defaultValue=""><option value="" disabled>Select category</option>{partnerCategories.map(c=><option key={c} value={c}>{names[c]}</option>)}</select></label><label>Business / professional name<input disabled={busy||pending.current!==null} name="businessName" required/></label><label>Responsible contact name<input disabled={busy||pending.current!==null} name="contactName" required autoComplete="name"/></label><div className="formTwo"><label>Email<input disabled={busy||pending.current!==null} name="email" type="email" required autoComplete="email"/></label><label>Phone<input disabled={busy||pending.current!==null} name="phone" type="tel" required autoComplete="tel"/></label></div><label>Operating area<input disabled={busy||pending.current!==null} name="area" placeholder="Province / district in Laos" required/></label><div className="verificationNote"><strong>Verification</strong><p>Submission does not activate selling. Required identity, license and settlement evidence is reviewed separately in private storage before approval.</p></div><button className="primaryButton" type="submit" disabled={busy}>{busy?"Submitting…":pending.current?"Retry same application":"Submit application"}</button>{notice&&<p className="formNotice" role="status">{notice}</p>}</form>}
