import {describe,it,expect,vi} from "vitest";import {createSmartPickupRequest,decideSmartPickupRequest,SmartPickupError} from "./postgres-smart-pickup";
function pool(query:ReturnType<typeof vi.fn>){return {connect:vi.fn().mockResolvedValue({query,release:vi.fn()})}}
describe("intercity smart pickup",()=>{
 it("rejects labels beyond the persisted 160 character limit before database access",async()=>{const p={connect:vi.fn()};await expect(createSmartPickupRequest(p as never,{userId:"u",bookingId:"b",latitude:0,longitude:0,label:"x".repeat(161)})).rejects.toMatchObject({code:"INVALID_INPUT"});expect(p.connect).not.toHaveBeenCalled()});
 it.each([{routeDetourMeters:0},{routeDetourSeconds:0}])("rejects declined route data before database access: %o",async data=>{const p={connect:vi.fn()};await expect(decideSmartPickupRequest(p as never,{userId:"u",partnerId:"p",requestId:"r",decision:"DECLINED",...data})).rejects.toMatchObject({code:"INVALID_INPUT"});expect(p.connect).not.toHaveBeenCalled()});
 it("creates only after server eligibility lookup",async()=>{const q=vi.fn().mockResolvedValueOnce({}).mockResolvedValueOnce({rows:[{smart_pickup_max_detour_m:2000}]}).mockResolvedValueOnce({rows:[{id:"r1",operator_status:"PENDING"}]}).mockResolvedValueOnce({});await expect(createSmartPickupRequest(pool(q) as never,{userId:"u",bookingId:"b",latitude:18.9,longitude:102.4,label:"Hotel"})).resolves.toEqual({requestId:"r1",status:"PENDING",maxDetourMeters:2000});expect(String(q.mock.calls[1][0])).toContain("vehicle_type='VIP_VAN'")});
 it("rejects ineligible bus or foreign booking",async()=>{const q=vi.fn().mockResolvedValueOnce({}).mockResolvedValueOnce({rows:[]}).mockResolvedValueOnce({});await expect(createSmartPickupRequest(pool(q) as never,{userId:"u",bookingId:"b",latitude:18.9,longitude:102.4})).rejects.toBeInstanceOf(SmartPickupError)});
 it("requires partner membership to decide",async()=>{const q=vi.fn().mockResolvedValueOnce({}).mockResolvedValueOnce({rows:[{allowed:false}]}).mockResolvedValueOnce({});await expect(decideSmartPickupRequest(pool(q) as never,{userId:"u",partnerId:"p",requestId:"r",decision:"ACCEPTED"})).rejects.toMatchObject({code:"ACCESS_DENIED"})});
});
